# Generated by Django 3.2.5 on 2022-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_add_name_measurement_unit_unique_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('name__len__gt', 0)), name='ingredients_ingredient_name_is_empty'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(check=models.Q(('measurement_unit__len__gt', 0)), name='ingredients_ingredient_measurement_unit_is_empty'),
        ),
    ]
