apiVersion : apps/v1
kind : Deployment
metadata:
  name : django-deployment
  namespace: foodgram-prod
  labels:
    app: foodgram-app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: foodgram
      component: django
  template:
    metadata:
      labels:
        project: foodgram
        component: django
    spec:
      containers:
        - name: backend
          image: ghcr.io/alex-men-vl/foodgram/backend:prod
          imagePullPolicy: IfNotPresent

          command: ['bash', './docker/django/gunicorn.sh']

          ports:
            - containerPort: 8000
              name: http-backend

          envFrom:
            - configMapRef:
                name: web-configmap
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django
                  key: secret_key
            - name: DJANGO_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database_name
            - name: DJANGO_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database_user
            - name: DJANGO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database_password
            - name: DJANGO_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database_host
            - name: DJANGO_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: django
                  key: database_port
            - name: DJANGO_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: access_key_id
            - name: DJANGO_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: secret_access_key
            - name: DJANGO_AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: bucket_name

---

apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: foodgram-prod
spec:
  type: ClusterIP
  selector:
    project: foodgram
    component: django
  ports:
    - port: 8000
      targetPort: http-backend
      protocol: TCP
      name: http-backend
