# This is just template. Add encoded values before use it.

apiVersion: v1
kind: Secret
metadata:
    name: django
type: Opaque
data:
    secret_key:
    database_name:
    database_user:
    database_password:
    database_host:
    database_port:

---

apiVersion: v1
kind: Secret
metadata:
    name: aws
type: Opaque
data:
    access_key_id:
    secret_access_key:
    bucket_name:
