# Generated by Django 3.2.5 on 2022-08-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0003_rename_user_field_verbose_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='favourites_favourite_recipe_user_unique_together'),
        ),
    ]
