version: '3.8'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: ./.envs/.env

  backend:
    image: 'foodgram_backend:dev'
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: gunicorn --reload config.wsgi:application --bind 0:8000
    volumes:
      - ./data:/data
      - static_data:/static
      - media_data:/media
    env_file: ./.envs/.env
    environment:
      DJANGO_DATABASE_HOST: db
    restart: unless-stopped
    depends_on:
      - db
      - frontend

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    image: foodgram_frontend
    volumes:
      - ./src/frontend:/app/result_build/

volumes:
  db_data:
  static_data:
  media_data:
