version: '3.8'
services:
  backend:
    <<: &backend
      image: ${BACKEND_IMAGE}
      build:
        target: production_build
        args:
          DJANGO_ENV: production
        cache_from:
          - ${BACKEND_IMAGE}
      environment:
        DJANGO_ENV: production
        AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
        DJANGO_AWS_ACCESS_KEY_ID: ${DJANGO_AWS_ACCESS_KEY_ID}
        DJANGO_AWS_SECRET_ACCESS_KEY: ${DJANGO_AWS_SECRET_ACCESS_KEY}
        DJANGO_AWS_STORAGE_BUCKET_NAME: ${DJANGO_AWS_STORAGE_BUCKET_NAME}

    ports:
      - 8000:8000

  frontend:
    <<: &frontend
      image: ${FRONTEND_IMAGE}
      build:
        context: .
        dockerfile: ./src/frontend/docker/node/Dockerfile
        cache_from:
          - ${FRONTEND_IMAGE}
    volumes:
      - ./src/frontend:/app/result_build/
