version: '3.8'
services:
  db:
    env_file: ./src/backend/.envs/.development/.env
    ports:
      # We only bind ports directly in development:
      - '5432:5432'

  backend:
    env_file: ./src/backend/.envs/.development/.env
    volumes:
      # We only mount source code in development:
      - ./src/backend:/code
      - ./data:/data

  # In production uses caddy
  nginx:
    build:
      context: .
      dockerfile: ./src/backend/docker/server/development/Dockerfile
    image: foodgram_nginx
    ports:
      - 80:80
    volumes:
      - ./src/frontend/build:/code/frontend/
      - ./docs/redoc.html:/code/frontend/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/code/frontend/api/docs/openapi-schema.yml
      - static_data:/code/admin_panel/static/
      - media_data:/code/admin_panel/media/
    depends_on:
      - backend
