version: '3.8'
services:
  db:
    ports:
      # We only bind ports directly in development:
      - '5432:5432'

  backend:
    volumes:
      # We only mount source code in development:
      - ./src/backend:/code

  # In production uses caddy
  nginx:
    build:
      context: .
      dockerfile: ./src/backend/docker/nginx/Dockerfile
    image: foodgram_nginx
    ports:
      - 80:80
    volumes:
      - frontend_static_data:/usr/src/app/frontend_data/static/
      - ./docs/redoc.html:/usr/src/app/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/src/app/api/docs/openapi-schema.yml
      - backend_static_data:/usr/src/app/backend_data/static/
      - backend_media_data:/usr/src/app/backend_data/media/
    depends_on:
      - backend
      - frontend
