version: '3.8'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backups:/backups
    env_file: ./src/backend/.envs/.env

  backend:
    <<: &backend
      image: 'foodgram_backend:dev'
      build:
        target: development_build
        context: .
        dockerfile: ./src/backend/docker/django/Dockerfile
        args:
          DJANGO_ENV: development
        cache_from:
          - foodgram_backend
    command: bash ./docker/django/gunicorn.sh
    volumes:
      - backend_static_data:/var/www/django/static
      - backend_media_data:/var/www/django/media
    env_file: ./src/backend/.envs/.env
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    <<: &frontend
      image: 'foodgram_frontend:dev'
      build:
        context: .
        dockerfile: ./src/frontend/docker/node/Dockerfile
        cache_from:
          - foodgram_frontend
    volumes:
      - frontend_static_data:/app/build/static
    command: serve -s build -l 3000
    ports:
      - 127.0.0.1:3000:3000

volumes:
  db_data:
  backend_static_data:
  backend_media_data:
  frontend_static_data:
