version: '3.8'
services:
#  caddy:
  backend:
    <<: &backend
      image: 'almen/foodgram_backend:prod'
      build:
        target: production_build
        args:
          DJANGO_ENV: production

    expose:
      - 8000
