version: '3.8'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: ./src/backend/.envs/.development/.env

  backend:
    <<: &backend
      image: 'foodgram_backend:dev'
      build:
        target: development_build
        context: .
        dockerfile: ./src/backend/docker/django/Dockerfile
        args:
          DJANGO_ENV: development
        cache_from:
          - foodgram_backend
    command: bash ./docker/django/gunicorn.sh
    volumes:
      - static_data:/var/www/django/static
      - media_data:/var/www/django/media
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    <<: &frontend
      image: 'foodgram_frontend:dev'
      build:
        context: .
        dockerfile: ./src/frontend/docker/node/Dockerfile
        cache_from:
          - foodgram_frontend
    volumes:
      - ./src/frontend:/app/result_build/

volumes:
  db_data:
  static_data:
  media_data:
