# Generated by Django 3.2.5 on 2022-07-15 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(blank=True, max_length=255, unique=True),
                ),
                (
                    'created',
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    'modified',
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='Название'
                    ),
                ),
                (
                    'hex_code',
                    models.CharField(
                        db_index=True,
                        max_length=7,
                        unique=True,
                        verbose_name='Цветовой HEX-код',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'unique_together': {('title', 'hex_code')},
            },
        ),
    ]
