# Generated by Django 3.2.5 on 2022-08-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_add_subscription_prevent_self_follow_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('subscriber', 'author'), name='subscriptions_subscription_subscriber_author_unique_together'),
        ),
    ]
