name: Build and Publish Docker Images

on:
  workflow_run:
    workflows: [ "Check code" ]
    types:
      - completed
    branches:
      - 'main'

jobs:
  check:
    name: Check changed files
    outputs:
      frontend: ${{ steps.check_files.outputs.frontend }}
      backend: ${{ steps.check_files.outputs.backend }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: check modified files
      id: check_files
      run: |
          echo ${{ github.event.workflow_run }}
          echo "=============== list modified files ==============="
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
          echo "========== check paths of modified files =========="
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > files.txt
          while IFS= read -r file; do
            echo $file
            if [[ $file == src/frontend/* ]]; then
              echo "::set-output name=frontend::true"
            elif [[ $file == src/backend/* ]]; then
              echo "::set-output name=backend::true"
            else
              echo "file does not belong to any service"
            fi
          done < files.txt

  frontend:
    needs: check
    name: Build and deploy frontend image
    if: needs.check.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build, tag, and push frontend image to Registry
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        CONTAINER: frontend
        IMAGE_NAME: foodgram_frontend
        IMAGE_TAG: dev
      run: |
        DOCKER_BUILDKIT=1 docker-compose build $CONTAINER
        docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

  backend:
    needs: check
    name: Build and deploy backend image
    if: needs.check.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Add environment variables to .env
      # FIX on production
      run: |
        echo DJANGO_ENV=development >> .env
        echo DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        echo DJANGO_DATABASE_HOST=${{ secrets.DJANGO_DATABASE_HOST }} >> .env
        echo DJANGO_DATABASE_PORT=${{ secrets.DJANGO_DATABASE_PORT }} >> .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build, tag, and push backend image to Registry
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        CONTAINER: backend
        IMAGE_NAME: foodgram_backend
        IMAGE_TAG: dev
      run: |
        DOCKER_BUILDKIT=1 docker-compose build $CONTAINER
        docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
