name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]

jobs:
  check:
    name: Check changed files
    outputs:
      frontend: ${{ steps.check_files.outputs.frontend }}
      backend: ${{ steps.check_files.outputs.backend }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: check modified files
      id: check_files
      run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file; do
            echo $file
            if [[ $file == src/frontend/* ]]; then
              echo "::set-output name=frontend::true"
            elif [[ $file == src/backend/* ]]; then
              echo "::set-output name=backend::true"
            else
              echo "file does not belong to any service"
            fi
          done < files.txt

  frontend:
    needs: check
    if: needs.check.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Publish backend to Registry
      uses: docker/build-push-action@v2
      with:
        context: src/frontend/docker/node/
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/foodgram_frontend:latest

  backend:
    needs: check
    if: needs.check.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Publish frontend to Registry
      uses: docker/build-push-action@v2
      with:
        context: src/backend/docker/django/
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/foodgram_backend:latest
