name: Check code

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
    paths:
      - '**.py'

  pull_request:
    types:
      - closed

jobs:
  linter:
    name: Run Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version' # Read python version from a file
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run flake8
        run: poetry run flake8

  tests:
    name: Run Pytest and MyPy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Stack
        run: DOCKER_BUILDKIT=1 docker-compose build backend

      - name: Run mypy
        run: docker-compose run --rm backend mypy .

      - name: Run Django Tests
        run: docker-compose run backend pytest --no-cov

      - name: Tear down the Stack
        run: docker-compose down
